---
- hosts: edeployservers
  vars:
    - pxemngr: false
  user: root
  tasks:
  - name: ensure needed packages for eDeploy are installed
    apt: pkg={{ item }} state=present
    with_items:
      - apache2
      - python-ipaddr
      - python-pip
      - git
      - rsync
      - debootstrap
  - name: extract eDeploy git repo
    git: repo=https://github.com/enovance/edeploy.git
         dest=/srv/edeploy force=no
  - name: create eDeploy config dir
    file: path=/etc/edeploy state=directory
  - name: copy config files
    cp: src=/srv/edeploy/config/* dest=/etc/edeploy
  - name: create edeploy CGI config
    ini_file: dest=/etc/edeploy.conf section=SERVER option=CONFIGDIR value=/etc/edeploy mode=0644
  - name: enable pxemngr support in CGI config
    ini_file: dest=/etc/edeploy.conf section=SERVER option=USEPXEMNGR value=True mode=0644
    when: pxemngr
  - name: set hw profiles dir in CGI config
    ini_file: dest=/etc/edeploy.conf section=SERVER option=HWDIR value=/var/lib/edeploy/hw mode=0644
  - name: set health dir in CGI config
    ini_file: dest=/etc/edeploy.conf section=SERVER option=HEALTHDIR value=/var/lib/edeploy/health mode=0644
  - name: set lock file in CGI config
    ini_file: dest=/etc/edeploy.conf section=SERVER option=LOCKFILE value=/var/lock/apache2/edeploy.lock mode=0644
  - name: set pxemngr URL in CGI config
    ini_file: dest=/etc/edeploy.conf section=SERVER option=PXEMNGRURL value=http://{{ ansible_default_ipv4["address"] }}/ mode=0644
    when: pxemngr
  - name: install eDeploy CGI script and set permissions for it
    file: src=/srv/edeploy/server/upload.py dest=/usr/lib/cgi-bin/upload.py state=link
  - name: install eDeploy health CGI script and set permissions for it
    file: src=/srv/edeploy/server/upload-health.py dest=/usr/lib/cgi-bin/upload-health.py state=link
  - name: owner of state file
    file: path=/etc/edeploy/state owner=www-data group=www-data
  - name: create directory for install trees
    file: path=/var/lib/debootstrap/install state=directory
  - name: create directory for hw profiles
    file: path=/var/lib/edeploy/hw state=directory owner=www-data group=www-data
  - name: create directory for health files
    file: path=/var/lib/edeploy/health state=directory owner=www-data group=www-data
  - name: link install trees location for web server
    file: src=/var/lib/debootstrap/install dest=/var/www/install state=link
  - name: list cmdb files 
    action: shell ls -1 /etc/edeploy/*.cmdb
    register: cmdbfiles
  - name: fix cmdb permissions
    file: path={{ item }} owner=www-data group=www-data
    with_items: ${cmdbfiles.stdout_lines}
  - name: create rsync conf file
    copy: src=rsyncd.conf dest=/etc/rsyncd.conf
  - name: enable rsync daemon
    lineinfile: dest=/etc/default/rsync regexp=RSYNC_ENABLE= line="RSYNC_ENABLE=true" state=present
    notify: start rsync daemon
  - name: install eDeploy profile in pxemngr
    template: src=edeploy.prof dest=/var/lib/tftpboot/pxelinux.cfg/profiles/edeploy.prof mode=0644
    notify: sync bootnames
    when: pxemngr
  handlers:
    - name: sync bootnames
      command: pxemngr syncbootnames
      notify: set default PXE boot to eDeploy
    - name: set default PXE boot to eDeploy
      command: pxemngr nextboot default edeploy
    - name: start rsync daemon
      service: name=rsync state=started
